# -*- python -*-
Import('env')

objs = env.Object(env.Glob('*.cpp'))

static_lib = env.StaticLibrary('meridian_common_static', objs)
shared_lib = env.SharedLibrary('meridian_common', objs)
env.Install('$LIB_DIR', shared_lib)

